### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mrrm92** [neXyon/audaspace#11]
Hello NeXyon.
As for your idea about refactoring AudaSpace, I had confirmation that the basic building blocks of any synth or audio processor lays in the Web Audio API.
If you want, I suggest using the Web Audio API in AudaSpace and provide Python nodes for your modules.

Hope this helps.

Relevant modules: https://dsp.stackexchange.com/questions/2475/what-are-the-basic-categories-of-operations-performed-on-audio-signals-to-create/2478#2478

**Comment by mrrm92** [comment]
No, nevermind: I just skimmed through the code and saw everything is alreadi implemented.
Side note: can I use a signal generator as an LFO?

Question: What is a f0 extractor?

**Comment by neXyon** [comment]
At the moment there are no human resources  to do the refactor. Also there is no need for any other library or design to base the refactor on. Otherwise you could just use that library...

About the signal generator as LFO: yes, just use low frequencies as the name suggests.

About the f0 extractor: I never heard this term before, maybe Google can help you.

**Comment by mrrm92** [comment]
No, neither Google. Unluck...
The more I ask about AudaSpace, day by day, the more I'm amazed by its simple power.

**Comment by mrrm92** [comment]
P.S.: Sorry man, I've never meant to teach you anything nor telling you how to work.
Pick my posts as like a children asks his dad/mum and discovers the world.

**Comment by mrrm92** [comment]
Excuse me to raise this again, I would just like to tell you I just found what is a f0 extractor.
The answer is here: http://www.justinsalamon.com/melody-extraction.html
