### ISSUE TITLE
upbge 0.3.0 in blender 2.8 is using audaSpace

### ISSUE THREAD

**Issue by BluePrintRandom** [neXyon/audaspace#21]
we are using audaSpace in upbge in blender 2.8

I play sounds with logic brick and it appears to cost quite a bit of CPU time,

is there anyway to move this logic use to another thread besides the 'main' game thread?

**Comment by BluePrintRandom** [comment]
https://github.com/UPBGE/blender/tree/upbge0.3

**Comment by neXyon** [comment]
Which logic are you talking about? Can you point me to the code? And what do you mean by "appears"? Did you profile the code and find out which calls take long? Is it calls to the audaspace API or your own?

In general you can multithread audaspace API calls, you just have to make sure they are thread safe, because audaspace doesn't insure thread safety by itself.

Also, audio mixing is done in a separate thread anyways.

**Comment by BluePrintRandom** [comment]
strangely enough this issue went away shortly after this -
not sure what was going on but it its fine now

I will close this thank you for audaspace!

**Comment by BluePrintRandom** [comment]
btw - https://github.com/UPBGE/blender/tree/upbge0.3 here is where bge is being restored to blender 2.8 * if you feel like helping youle and loki.
