### ISSUE TITLE
UPBGE crashing due to "Unable to initialise audio" + aud python module load

### ISSUE THREAD

**Issue by lordloki** [neXyon/audaspace#22]
Hi Nexyon,

we received an issue report on UPBGE pointing out to a crash. The issue is here: https://github.com/UPBGE/upbge/issues/1150

We investigated and came to the conclusion that the problem was that it was not possible to initialize the audio ("Unable to initialise audio") and when the python module (aud) was loaded, the crash occurred. The fix we made is here: https://github.com/UPBGE/upbge/commit/2ccc3063af74c266b4b03cbe509bccbb9a8fe09c.
Can you guide us about the possible causes of the audio not being able to be initialized (the user has the updated drivers)?

Thanks in advance

**Comment by neXyon** [comment]
Hi!

This is weird! It can't have anything to do with audio. Should be a python problem, since all that happens there is the initialization of the python module (no audio devices are opened or so). To dig further, could you try to find out where exactly in PyInit_aud() it fails/returns? It could only return nullptr there if one of  the python class initializations or the python module initialization fails... Those are all python functions though.

Cheers

**Comment by lordloki** [comment]
The nullptr is return in check:
´´´
	if(!initializeSound())
		return nullptr;
´´´

**Comment by neXyon** [comment]
Can you then let me know what the following prints on stderr, when you change the function in PySound.cpp:

```
bool initializeSound()
{
	import_array();

	if(PyType_Ready(&SoundType) < 0)
	{
		PyErr_Print();
		return false;
	}

	return true;
}
```

**Comment by lordloki** [comment]
Hi Nexyon,

the bug was solved. The issue was related to the user's Python has a mix the environment and Blender site-packages.
Fix for Blender: https://developer.blender.org/rB79a58eef059ffc3f12d11bd68938cfb1b4cd2462
Additional fix for UPBGE: https://github.com/UPBGE/upbge/commit/00ae19e59d44ce26cc55e922a69755b07d3f1581

Thanks for your help and time. I close the report.
