### ISSUE TITLE
OpenAL device is not running Stereo correctly

### ISSUE THREAD

**Issue by RafaelTavars** [neXyon/audaspace#44]
The OpenAL Device seems to lack Stereo accuracy after this commit I think
https://github.com/blender/blender/commit/986267300ba42a5c99d2802cd701803dd558e389

I did some tests with a song on each side and it seems that the Stereo is not 100% for some reason, It's like trying to play audio in mono.

https://github.com/user-attachments/assets/61d36a56-ca4d-4a17-b3b0-d334ad1a4697

**Comment by neXyon** [comment]
It's not exactly accuracy that is missing. OpenAL is mostly using the OpenAL Soft implementation which switched to use ambisonics a while ago which is why stereo sounds different using it. There is not much we can do about this. However, all other backends render audio in the same way as Blender does for exporting the audio, so I highly suggest you use another backend instead of OpenAL. There is no real benefit to use OpenAL. Rendering audio differently is actually a disadvantage. The default backend which on Windows is WASAPI is the default for a good reason :)

**Comment by RafaelTavars** [comment]
> As far as I know, no. You could use an old version [OpenAL Soft](https://github.com/kcat/openal-soft), i.e. 1.16 or earlier. Otherwise you may ask there, but I think to remember that the old way is simply not supported anymore.
> 
> Not sure about the other features that you implemented, but audaspace also supports reverb through the Convolver effect which you have to give the impulse response of the reverb.


That was it!! I just had to downgrade OpenAL, bruh I wasted hours checking the audaspace code .. 😆 

Now this is really strange, I tested several versions and with each update of the Blender dll the audio gets worse.

Well, I think updating OpenAL shouldn't bring many benefits, I just needed to modify the code a little to make it work on the old one.

In the old issues I saw you mentioning that there is support for reverb with convolver but I couldn't get it to work, I used the OpenAL efx.h with AL_REVERB, it works very well in real time.

Here you can see the difference between the versions, and the quality gets worse with each update. In Blender 4.1 the audio seems extremely muffled. idk why

https://github.com/user-attachments/assets/e9fc8361-afa0-4d65-a5b2-b9b15c3f13a3

Thank you @neXyon! 
I don't think I would have ever checked out the OpenAL version if you hadn't mentioned it. Cheers and thanks again!😄
