### ISSUE TITLE
effects and oscillators (in the blender version)

### ISSUE THREAD

**Issue by Berserk82** [neXyon/audaspace#8]
Hello.
I'd like to know, exactly, in the blender version of audaspace, which waveforms are available for oscillators, and which effects are available (I'm interested in: compressor, delay, reverb and eq, but please list them all).

Thanks in advance for either. 

Cheers.

**Comment by neXyon** [comment]
Hi,

the easiest way to find out is to have a look at the (bindings) documentation: http://audaspace.github.io/bindings/sound.html

For the ones you're interested in: delay and reverb are there, the other two not.

Cheers

**Comment by mrrm92** [comment]
Excuse me, what about LFO?

**Comment by neXyon** [comment]
At the moment there are no plans to do so. A waveshaper is a complex filter, that already needs a good design when it is developed so that users have enough but not overly complex creative freedom, when they use it. That's something I don't see myself capable of doing at the moment and unfortunately there's nobody else working on audaspace at the moment.

**Comment by mrrm92** [comment]
Man, I wish I could help!
If I knew enough I would.
Thanks anyhow.
